import type { Program, TypeDeclaration, PromptDeclaration, ChainDeclaration } from "../ast/nodes";
import {
  buildTypeRegistry,
  generateTypeDeclaration,
  generatePromptDeclaration,
  type CompiledMetadata,
} from "./code-generator";
import { buildCallableRegistry, generateChain } from "./chain-compiler";
import pkg from "../../package.json";

export function compile(program: Program, sourceFile: string): string {
  const timestamp = new Date().toISOString();
  const parts: string[] = [];

  parts.push(`// AUTO-GENERATED by PromptLang v${pkg.version} — do not edit manually.`);
  parts.push(`// Source: ${sourceFile}`);
  parts.push(`// Generated at: ${timestamp}`);
  parts.push("");
  parts.push(`import type { PromptClient, PromptRequest } from "promptlang/runtime";`);
  parts.push("");

  const registry = buildTypeRegistry(program);
  const callableRegistry = buildCallableRegistry(program);
  const meta = extractMetadata(program);

  const typeDecls = program.declarations.filter(
    (d): d is TypeDeclaration => d.kind === "TypeDeclaration"
  );
  const promptDecls = program.declarations.filter(
    (d): d is PromptDeclaration => d.kind === "PromptDeclaration"
  );
  const chainDecls = program.declarations.filter(
    (d): d is ChainDeclaration => d.kind === "ChainDeclaration"
  );

  if (typeDecls.length > 0) {
    parts.push("// ---- Types ----");
    parts.push("");
    for (const decl of typeDecls) {
      parts.push(generateTypeDeclaration(decl));
      parts.push("");
    }
  }

  if (promptDecls.length > 0) {
    parts.push("// ---- Prompt definitions ----");
    parts.push("");
    for (const decl of promptDecls) {
      parts.push(generatePromptDeclaration(decl, meta, registry));
      parts.push("");
    }
  }

  if (chainDecls.length > 0) {
    parts.push("// ---- Chain ----");
    parts.push("");
    for (const decl of chainDecls) {
      parts.push(generateChain(decl, callableRegistry));
      parts.push("");
    }
  }

  return parts.join("\n");
}

function extractMetadata(program: Program): CompiledMetadata {
  const meta: CompiledMetadata = {};
  for (const m of program.metadata) {
    switch (m.kind) {
      case "VersionMetadata":
        meta.version = m.value;
        break;
      case "ModelMetadata":
        meta.model = m.value;
        break;
      case "TemperatureMetadata":
        meta.temperature = m.value;
        break;
      case "MaxTokensMetadata":
        meta.maxTokens = m.value;
        break;
    }
  }
  return meta;
}
