import type { Program, TypeDeclaration, PromptDeclaration, ChainDeclaration } from "../../ast/nodes";
import {
  buildPythonTypeRegistry,
  buildCallableRegistryForPython,
  generatePythonTypeDeclaration,
  generatePythonPromptDeclaration,
  generatePythonChain,
  type CompiledPythonMetadata,
} from "./python-code-generator";
import pkg from "../../../package.json";

/** Compiles a PromptLang Program to a Python source string. */
export function compilePython(program: Program, sourceFile: string): string {
  const timestamp = new Date().toISOString();
  const parts: string[] = [];

  // Header
  parts.push(`"""`);
  parts.push(`AUTO-GENERATED by PromptLang v${pkg.version} — do not edit manually.`);
  parts.push(`Source: ${sourceFile}`);
  parts.push(`Generated at: ${timestamp}`);
  parts.push(`"""`);
  parts.push("");
  parts.push("from __future__ import annotations");

  const needsLiteral = hasEnumOrLiteral(program);
  const needsTypedDict = hasStructOrParams(program);

  const typingImports: string[] = [];
  if (needsLiteral) typingImports.push("Literal");
  if (needsTypedDict) typingImports.push("TypedDict");

  // Always import NotRequired in case structs have optional fields
  typingImports.push("NotRequired");

  if (typingImports.length > 0) {
    parts.push(`from typing import ${typingImports.join(", ")}`);
  }
  parts.push(`from .promptlang_runtime import PromptClient, PromptRequest`);
  parts.push("");

  const registry = buildPythonTypeRegistry(program);
  const callableRegistry = buildCallableRegistryForPython(program);
  const meta = extractPythonMetadata(program);

  const typeDecls = program.declarations.filter(
    (d): d is TypeDeclaration => d.kind === "TypeDeclaration"
  );
  const promptDecls = program.declarations.filter(
    (d): d is PromptDeclaration => d.kind === "PromptDeclaration"
  );
  const chainDecls = program.declarations.filter(
    (d): d is ChainDeclaration => d.kind === "ChainDeclaration"
  );

  if (typeDecls.length > 0) {
    parts.push("# ---- Types ----");
    parts.push("");
    for (const decl of typeDecls) {
      parts.push(generatePythonTypeDeclaration(decl));
      parts.push("");
    }
  }

  if (promptDecls.length > 0) {
    parts.push("# ---- Prompt definitions ----");
    parts.push("");
    for (const decl of promptDecls) {
      parts.push(generatePythonPromptDeclaration(decl, meta, registry));
      parts.push("");
    }
  }

  if (chainDecls.length > 0) {
    parts.push("# ---- Chains ----");
    parts.push("");
    for (const decl of chainDecls) {
      parts.push(generatePythonChain(decl, callableRegistry));
      parts.push("");
    }
  }

  return parts.join("\n");
}

function extractPythonMetadata(program: Program): CompiledPythonMetadata {
  const meta: CompiledPythonMetadata = {};
  for (const m of program.metadata) {
    switch (m.kind) {
      case "VersionMetadata": meta.version = m.value; break;
      case "ModelMetadata": meta.model = m.value; break;
      case "TemperatureMetadata": meta.temperature = m.value; break;
      case "MaxTokensMetadata": meta.maxTokens = m.value; break;
    }
  }
  return meta;
}

function hasEnumOrLiteral(program: Program): boolean {
  return program.declarations.some(
    (d) => d.kind === "TypeDeclaration" && d.definition.kind === "EnumType"
  );
}

function hasStructOrParams(program: Program): boolean {
  return program.declarations.some((d) => {
    if (d.kind === "TypeDeclaration" && d.definition.kind === "StructType") return true;
    if (d.kind === "PromptDeclaration") return true;
    if (d.kind === "ChainDeclaration") return true;
    return false;
  });
}
