import { describe, test, expect } from "bun:test";
import { compilePython } from "./python-compiler";
import { getPythonRuntimeSource } from "./python-runtime-template";
import { tokenize } from "../../lexer/lexer";
import { parse } from "../../parser/parser";
import { mkdir, writeFile, rm } from "node:fs/promises";

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function parseSource(src: string) {
  return parse(tokenize(src));
}

function compile(src: string): string {
  return compilePython(parseSource(src), "test.prompt");
}

// Check if python3 is available for integration tests
const pythonAvailable = Bun.spawnSync(["which", "python3"]).exitCode === 0;
if (!pythonAvailable) {
  console.warn("⚠  python3 not available — skipping Python integration tests");
}

// ---------------------------------------------------------------------------
// Header
// ---------------------------------------------------------------------------

describe("Python compiler — header", () => {
  test("AUTO-GENERATED comment is present", () => {
    const out = compile(`@version "1.0.0"\nprompt greet() -> string { user: "Hi" }`);
    expect(out).toContain("AUTO-GENERATED by PromptLang");
  });

  test("source filename appears in header", () => {
    const out = compilePython(parseSource(`@version "1.0.0"\nprompt greet() -> string { user: "Hi" }`), "my-file.prompt");
    expect(out).toContain("Source: my-file.prompt");
  });

  test("ISO timestamp appears in header", () => {
    const out = compile(`@version "1.0.0"\nprompt greet() -> string { user: "Hi" }`);
    expect(out).toMatch(/Generated at: \d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}/);
  });

  test("from __future__ import annotations is present", () => {
    const out = compile(`@version "1.0.0"\nprompt greet() -> string { user: "Hi" }`);
    expect(out).toContain("from __future__ import annotations");
  });

  test("runtime import uses relative .promptlang_runtime", () => {
    const out = compile(`@version "1.0.0"\nprompt greet() -> string { user: "Hi" }`);
    expect(out).toContain("from .promptlang_runtime import PromptClient, PromptRequest");
  });
});

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

describe("Python compiler — type declarations", () => {
  test("enum type produces Literal + _VALUES list", () => {
    const out = compile(`type Status = enum { active, inactive, pending }`);
    expect(out).toContain(`Status = Literal["active", "inactive", "pending"]`);
    expect(out).toContain(`_STATUS_VALUES`);
    expect(out).toContain(`"active", "inactive", "pending"`);
  });

  test("struct type produces TypedDict class", () => {
    const out = compile(`type Invoice = struct { amount: number, vendor: string }`);
    expect(out).toContain("class Invoice(TypedDict):");
    expect(out).toContain("    amount: float");
    expect(out).toContain("    vendor: str");
  });

  test("struct optional field uses NotRequired", () => {
    const out = compile(`type Invoice = struct { amount: number, ref?: string }`);
    expect(out).toContain("    ref: NotRequired[str]");
  });
});

// ---------------------------------------------------------------------------
// Prompt declarations
// ---------------------------------------------------------------------------

describe("Python compiler — prompt declarations", () => {
  test("prompt with no params generates empty TypedDict", () => {
    const out = compile(`@version "1.0.0"\nprompt greet() -> string { user: "Hi" }`);
    expect(out).toContain("class GreetInput(TypedDict):");
    expect(out).toContain("    pass");
  });

  test("prompt with one string param → TypedDict field as str", () => {
    const out = compile(`@version "1.0.0"\nprompt greet(name: string) -> string { user: "Hi {{name}}" }`);
    expect(out).toContain("class GreetInput(TypedDict):");
    expect(out).toContain("    name: str");
  });

  test("prompt with multiple params → all fields in TypedDict", () => {
    const out = compile(`@version "1.0.0"\nprompt calc(x: number, y: boolean) -> string { user: "test" }`);
    expect(out).toContain("    x: float");
    expect(out).toContain("    y: bool");
  });

  test("metadata @model appears in META constant", () => {
    const out = compile(`@model claude-haiku-4-5\nprompt greet() -> string { user: "Hi" }`);
    expect(out).toContain(`GREET_META`);
    expect(out).toContain(`"model": "claude-haiku-4-5"`);
  });

  test("metadata @temperature appears in META constant", () => {
    const out = compile(`@temperature 0.5\nprompt greet() -> string { user: "Hi" }`);
    expect(out).toContain(`"temperature": 0.5`);
  });

  test("META constant is SCREAMING_SNAKE_CASE", () => {
    const out = compile(`@version "1.0.0"\nprompt classify_ticket() -> string { user: "test" }`);
    expect(out).toContain("CLASSIFY_TICKET_META");
  });

  test("function is async def", () => {
    const out = compile(`@version "1.0.0"\nprompt greet() -> string { user: "Hi" }`);
    expect(out).toContain("async def greet(");
  });

  test("function has return type annotation", () => {
    const out = compile(`@version "1.0.0"\nprompt greet() -> string { user: "Hi" }`);
    expect(out).toContain(") -> str:");
  });

  test("enum return type generates validation against _VALUES", () => {
    const out = compile(`
type Cat = enum { bug, feature }
prompt classify() -> Cat { user: "test" }`);
    expect(out).toContain("_CAT_VALUES");
    expect(out).toContain("if raw not in");
  });

  test("struct return type generates JSON parse validation", () => {
    const out = compile(`
type Invoice = struct { amount: number }
prompt extract() -> Invoice { user: "test" }`);
    expect(out).toContain("_json.loads(raw)");
    expect(out).toContain("JSONDecodeError");
  });

  test("number return type generates float() conversion", () => {
    const out = compile(`@version "1.0.0"\nprompt count() -> number { user: "test" }`);
    expect(out).toContain("float(raw)");
  });

  test("boolean return type generates true/false check", () => {
    const out = compile(`@version "1.0.0"\nprompt flag() -> boolean { user: "test" }`);
    expect(out).toContain("lower not in (\"true\", \"false\")");
  });

  test("template {{var}} becomes f-string with input['var']", () => {
    const out = compile(`@version "1.0.0"\nprompt greet(name: string) -> string { user: "Hi {{name}}" }`);
    expect(out).toContain(`{input['name']}`);
    expect(out).toContain('f"');
  });

  test("system section appears in messages", () => {
    const out = compile(`@version "1.0.0"\nprompt greet() -> string { system: "You are a greeter." user: "Hi" }`);
    expect(out).toContain('"role": "system"');
    expect(out).toContain("You are a greeter.");
  });

  test("TypedDict input type name is PascalCase + Input", () => {
    const out = compile(`@version "1.0.0"\nprompt classify_ticket() -> string { user: "test" }`);
    expect(out).toContain("class ClassifyTicketInput(TypedDict):");
  });

  test("type reference return type uses the declared name", () => {
    const out = compile(`
type Category = enum { a, b }
prompt classify() -> Category { user: "test" }`);
    expect(out).toContain("-> Category:");
  });
});

// ---------------------------------------------------------------------------
// Multiline strings
// ---------------------------------------------------------------------------

describe("Python compiler — multiline strings", () => {
  test("triple-quoted system prompt is preserved", () => {
    const out = compile(`@version "1.0.0"\nprompt greet() -> string {
  system: """
    You are a helper.
  """
  user: "Hi"
}`);
    expect(out).toContain('"""');
    expect(out).toContain("You are a helper.");
  });
});

// ---------------------------------------------------------------------------
// Chain
// ---------------------------------------------------------------------------

describe("Python compiler — chains", () => {
  test("simple chain with one step compiles", () => {
    const out = compile(`
@version "1.0.0"
prompt summarize(text: string) -> string { user: "Summarize: {{text}}" }
chain process(text: string) -> string {
  step summary = summarize(text: text)
  return summary
}`);
    expect(out).toContain("async def process(");
    expect(out).toContain("summary = await summarize(");
    expect(out).toContain("return summary");
  });

  test("chain input uses dict access input['param']", () => {
    const out = compile(`
@version "1.0.0"
prompt greet(name: string) -> string { user: "Hi {{name}}" }
chain run(name: string) -> string {
  step result = greet(name: name)
  return result
}`);
    expect(out).toContain(`"name": input["name"]`);
  });

  test("chain TypedDict is PascalCase + Input", () => {
    const out = compile(`
@version "1.0.0"
prompt greet(name: string) -> string { user: "Hi {{name}}" }
chain run_all(name: string) -> string {
  step r = greet(name: name)
  return r
}`);
    expect(out).toContain("class RunAllInput(TypedDict):");
  });

  test("boolean literal in chain is True/False (Python)", () => {
    const out = compile(`
@version "1.0.0"
prompt check(flag: boolean) -> string { user: "test" }
chain run() -> string {
  step r = check(flag: true)
  return r
}`);
    expect(out).toContain("True");
  });
});

// ---------------------------------------------------------------------------
// Integration: py_compile
// ---------------------------------------------------------------------------

test.if(pythonAvailable)("generated Python parses with ast.parse (classify-ticket)", async () => {
  const source = await Bun.file("docs/examples/classify-ticket.prompt").text();
  const ast = parse(tokenize(source));
  const generated = compilePython(ast, "classify-ticket.prompt");
  const runtime = getPythonRuntimeSource();

  const tmpDir = "/tmp/promptlang-python-test";
  await mkdir(tmpDir, { recursive: true });
  await writeFile(`${tmpDir}/classify_ticket.py`, generated);
  await writeFile(`${tmpDir}/promptlang_runtime.py`, runtime);
  await writeFile(`${tmpDir}/__init__.py`, "");

  try {
    // 1. py_compile — syntax check
    const compile = Bun.spawnSync(["python3", "-m", "py_compile", `${tmpDir}/classify_ticket.py`]);
    if (compile.exitCode !== 0) {
      const stderr = new TextDecoder().decode(compile.stderr);
      throw new Error(`py_compile failed:\n${stderr}\n\nGenerated:\n${generated}`);
    }
    expect(compile.exitCode).toBe(0);

    // 2. ast.parse — both files are syntactically valid Python
    const importTest = `
import ast
with open('${tmpDir}/classify_ticket.py') as f:
    ast.parse(f.read())
with open('${tmpDir}/promptlang_runtime.py') as f:
    ast.parse(f.read())
print("OK")
`.trim();
    const result = Bun.spawnSync(["python3", "-c", importTest]);
    if (result.exitCode !== 0) {
      const stderr = new TextDecoder().decode(result.stderr);
      throw new Error(`ast.parse failed:\n${stderr}`);
    }
    expect(result.exitCode).toBe(0);
  } finally {
    await rm(tmpDir, { recursive: true, force: true });
  }
});

test.if(pythonAvailable)("generated Python parses with ast.parse (extract-invoice struct)", async () => {
  const source = await Bun.file("docs/examples/extract-invoice.prompt").text();
  const ast = parse(tokenize(source));
  const generated = compilePython(ast, "extract-invoice.prompt");

  const tmpDir = "/tmp/promptlang-python-invoice-test";
  await mkdir(tmpDir, { recursive: true });
  await writeFile(`${tmpDir}/extract_invoice.py`, generated);
  await writeFile(`${tmpDir}/promptlang_runtime.py`, getPythonRuntimeSource());

  try {
    const result = Bun.spawnSync(["python3", "-m", "py_compile", `${tmpDir}/extract_invoice.py`]);
    if (result.exitCode !== 0) {
      const stderr = new TextDecoder().decode(result.stderr);
      throw new Error(`py_compile failed:\n${stderr}\n\nGenerated:\n${generated}`);
    }
    expect(result.exitCode).toBe(0);
  } finally {
    await rm(tmpDir, { recursive: true, force: true });
  }
});
